@url = http://localhost:3001/api
@json = Content-Type: application/json
###
get {{url}}/user?user=小刘&age=12

###
post {{url}}/user/register
{{json}}

{
    "username": "wangmin",
    "password": "123456"
}

###
POST {{url}}/user/login
{{json}}

{
    "username": "user1",
    "password": "123456"
}
